# Generated by Django 4.1.1 on 2022-09-22 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='puplished',
            new_name='published',
        ),
    ]
